name: check

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Check toolchain
        run: rustup show

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit

  fmt:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Check toolchain
      run: rustup show

    - name: Install cargo fmt
      run: rustup component add rustfmt

    - name: Run cargo fmt
      run: cargo fmt -v --all -- --check

  clippy:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Check toolchain
      run: rustup show

    - name: Install cargo clippy
      run: rustup component add clippy

    - name: Run cargo clippy
      run: cargo clippy --all-features -- -D warnings
