name: cargo publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Publish crate
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
