name: cargo fmt
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  fmt:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Check toolchain
      run: rustup show

    - name: Install cargo fmt
      run: rustup component add rustfmt

    - name: Run cargo fmt
      run: cargo fmt -v --all -- --check
