name: cargo clippy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  clippy:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Check toolchain
      run: rustup show

    - name: Install cargo clippy
      run: rustup component add clippy

    - name: Run cargo clippy
      run: cargo clippy --all-features -- -D warnings
