name: cargo audit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v2

      - name: Check toolchain
        run: rustup show

      - name: Install cargo audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
