name: tag

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  check:
    uses: ./.github/workflows/check.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Parse version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Run builds
      uses: ./.github/workflows/build.yml
      with:
        version: ${{ env.VERSION }}

  release:
    name: release
    runs-on: ubuntu-22.04
    needs: [test, build]
    steps:
    - name: Parse version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create GitHub release
      id: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        files: artifacts/**/*
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Publish crate
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
