name: push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    uses: ./.github/workflows/groups/check.yml

  test:
    uses: ./.github/workflows/groups/test.yml
