name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  test:
    uses: ./.github/workflows/cargo-test.yml

  build:
    uses: ./.github/workflows/cargo-build.yml

  release:
    name: release
    runs-on: ubuntu-22.04
    needs: [test, build]
    steps:
      - name: Parse version tag
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Version: ${{ env.VERSION }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: artifacts/**/*
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
    - name: Fetch repository
      uses: actions/checkout@v2

    - name: Publish crate
      run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
